#!/bin/bash

echo "{\"location\": \"OutOfOffice\", \"info\": \"just not up for it\"}" | curl -T - -H "Content-Type: application/json" http://localhost:8181/workers/martin.schinz@pebblecode.com/default -v 

